server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index "Barber Booking (Offline) (1).html";

    location / {
        try_files $uri $uri/ =404;
    }

    types {
        application/javascript jsx;
        text/javascript js;
    }
}
